In [2]:
import numpy as np


In [3]:
a= np.array([1,2,3,4,5])
print (a,type[a],a.dtype)

[1 2 3 4 5] type[array([1, 2, 3, 4, 5])] int64


In [4]:
a2=np.array([[1,2,3],[2,3,4]])
print(a2)
print(a2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [5]:
a2=np.array([
    'A','B','C'
])
print(a2)

['A' 'B' 'C']


In [6]:
ar=np.ones(4)
print(ar)

[1. 1. 1. 1.]


In [7]:
array1 = np.linspace(1,10,num=10)
print(array1)

array2 = np.linspace(1,2,num=2)
print(array2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2.]


In [20]:
a=np.array([1,2,3,4,5])
b=a
print(b[2])
c=a.copy()
print(c[2])

a[2]=100
print(a)
print(b[2])

b[1]=200
print(a) 
print(c[2])



d= a.view()
print(d[2])
d[2]=300
print(a)
print(b[2])

3
3
[  1   2 100   4   5]
100
[  1 200 100   4   5]
3
100
[  1 200 300   4   5]
300


In [22]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a3=np.concatenate((a1,a2))
print(a3)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
a=np.array(
    [[1,2,3,4],
            [5,6,7,8]]
            )
print(a.shape)
print(a.ndim)



an=np.array([1,2,3,4,5],ndmin=5)
print(an)
print(an.shape)

(2, 4)
2
[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [36]:
arr=np.array([[3,43,3,4,5],[34,23,432,24,4]])
for i in np.nditer(arr):
    print(i)

3
43
3
4
5
34
23
432
24
4


In [41]:
a=np.array([[1,2],[6,7]])
b=np.array([[6,7],[1,2]])
r=a.dot(b)
print(r)

[[ 8 11]
 [43 56]]
