In [2]:
import numpy as np


In [5]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a[[0,1,2],:] = a[[2,0,1],:]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [7]:
#changing rows to columns 
a = a.T
print(a)


[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [13]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(arr.shape)

arr[[0,1,2],:,:]=arr[[2,0,1],:,:]
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [17]:
#file operations
with open("file1.txt","w") as f:
    f.write("1.2.3.2.2.3\n4.9.3.5.1.1\n2.4.2.4.1.3")

data = np.loadtxt("file1.txt", delimiter=".")
print(data)

[[1. 2. 3. 2. 2. 3.]
 [4. 9. 3. 5. 1. 1.]
 [2. 4. 2. 4. 1. 3.]]


In [ ]:
"""1x+2y=5
2x+3y=8"""
arr1=np.array([[1,2],[2,3]])
arr2=np.array([5,8])

res = np.linalg.solve(arr1,arr2)
print(res)

[1. 2.]
