In [2]:
import numpy as np


In [3]:
a= np.array([1,2,3,4,5])
print (a,type[a],a.dtype)

[1 2 3 4 5] type[array([1, 2, 3, 4, 5])] int64


In [4]:
a2=np.array([[1,2,3],[2,3,4]])
print(a2)
print(a2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [5]:
a2=np.array([
    'A','B','C'
])
print(a2)

['A' 'B' 'C']


In [6]:
ar=np.ones(4)
print(ar)

[1. 1. 1. 1.]


In [7]:
array1 = np.linspace(1,10,num=10)
print(array1)

array2 = np.linspace(1,2,num=2)
print(array2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2.]


In [8]:
a=np.array([1,2,3,4,5])
b=a
print(b[2])
c=a.copy()
print(c[2])

a[2]=100
print(a)
print(b[2])

b[1]=200
print(a) 
print(c[2])



d= a.view()
print(d[2])
d[2]=300
print(a)
print(b[2])

3
3
[  1   2 100   4   5]
100
[  1 200 100   4   5]
3
100
[  1 200 300   4   5]
300


In [9]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a3=np.concatenate((a1,a2))
print(a3)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a=np.array(
    [[1,2,3,4],
            [5,6,7,8]]
            )
print(a.shape)
print(a.ndim)



an=np.array([1,2,3,4,5],ndmin=5)
print(an)
print(an.shape)

(2, 4)
2
[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [11]:
arr=np.array([[3,43,3,4,5],[34,23,432,24,4]])
for i in np.nditer(arr):
    print(i)

3
43
3
4
5
34
23
432
24
4


In [12]:
a=np.array([[1,2],[6,7]])
b=np.array([[6,7],[1,2]])
r=a.dot(b)
print(r)

[[ 8 11]
 [43 56]]


In [16]:
#transpose
a2=np.array([[1,2,3],[4,5,6],[32,23,3]])
print(a2)
print(a2.T)
print(np.transpose(a2))

[[ 1  2  3]
 [ 4  5  6]
 [32 23  3]]
[[ 1  4 32]
 [ 2  5 23]
 [ 3  6  3]]
[[ 1  4 32]
 [ 2  5 23]
 [ 3  6  3]]


In [21]:
#join array
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.concatenate([arr1,arr2],axis=0)
print(arr3)

[1 2 3 4 5 6 7 8]


In [28]:
a=np.arange(9)
print(a)
print(np.split(a,3))

for i,a in enumerate(np.split(a,3)):
    print(i,a)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
0 [0 1 2]
1 [3 4 5]
2 [6 7 8]


In [32]:
#append
a=np.array([[1,2,3],[3,4,5]])
res = np.append(a,[[6,7,8],[2,41,1]],axis=1)
print(res)

[[ 1  2  3  6  7  8]
 [ 3  4  5  2 41  1]]


In [40]:
#insert
a=np.array([[1,2],[3,4],[5,6]])
print(a)

print(np.insert(a,1,[7,2],axis=0))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [7 2]
 [3 4]
 [5 6]]


In [44]:
#delete
a=np.arange(12).reshape(3,4)
print(a)

print(np.delete(a,1,axis=0))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [50]:
a=np.arange(12).reshape(3,4 )
res= np.flip(a)
print(res)

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [55]:
#sort
a=np.array([[3,2,4],[1,5,4]])
print(np.sort(a))

[[2 3 4]
 [1 4 5]]


In [64]:
#argmax
a=np.array([[1,2234],[332,23224]])
res=np.argmax(a)
print(res)


3


In [66]:
  #size
a=np.array([[1,2],[3,4]])
print(a.size)

4


In [67]:
#arithmetic
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[4,3,3],[23,3,1]])
print(a%b)

[[1 2 0]
 [2 0 0]]
